<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AkashicRecords.Domain\AkashicRecords.Domain.csproj" />
    <ProjectReference Include="..\AkashicRecords.Infrastructure\AkashicRecords.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="setup-tools.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
